// <auto-generated />
using System;
using AccountAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190702044829_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CheckedOutStatus");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("EmailPassword")
                        .IsRequired();

                    b.Property<int>("EventId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("AccountId");

                    b.HasIndex("EventId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountAPI.Models.AccountProfile", b =>
                {
                    b.Property<int>("AccountProfileId");

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("SecretAnswer1");

                    b.Property<string>("SecretAnswer2");

                    b.Property<string>("SecretAnswer3");

                    b.Property<string>("SecretQuestion1");

                    b.Property<string>("SecretQuestion2");

                    b.Property<string>("SecretQuestion3");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("AccountProfileId");

                    b.ToTable("AccountProfiles");
                });

            modelBuilder.Entity("AccountAPI.Models.Code", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeString")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("GameId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<bool>("UsedStatus");

                    b.HasKey("CodeId");

                    b.HasIndex("CodeString")
                        .IsUnique();

                    b.HasIndex("GameId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("AccountAPI.Models.ControllerType", b =>
                {
                    b.Property<int>("ControllerTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ControllerTypeId");

                    b.ToTable("ControllerTypes");

                    b.HasData(
                        new
                        {
                            ControllerTypeId = 1,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(9609),
                            Type = "Touch",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(9828)
                        },
                        new
                        {
                            ControllerTypeId = 2,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(45),
                            Type = "Keyboard & Mouse",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(49)
                        },
                        new
                        {
                            ControllerTypeId = 3,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(57),
                            Type = "Xbox",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(59)
                        },
                        new
                        {
                            ControllerTypeId = 4,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(66),
                            Type = "Steering Wheel",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(68)
                        });
                });

            modelBuilder.Entity("AccountAPI.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("EventId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(1547),
                            Location = "Chicago",
                            Name = "IEM",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(1760)
                        });
                });

            modelBuilder.Entity("AccountAPI.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ConnectionType");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("URLToDocumentation")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AccountAPI.Models.GameAccount", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("AccountId");

                    b.HasKey("GameId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("GameAccount");
                });

            modelBuilder.Entity("AccountAPI.Models.GameControllerType", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("ControllerTypeId");

                    b.HasKey("GameId", "ControllerTypeId");

                    b.HasIndex("ControllerTypeId");

                    b.ToTable("GameControllerType");
                });

            modelBuilder.Entity("AccountAPI.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("PlatformId");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("AccountAPI.Models.GameRating", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("RatingId");

                    b.HasKey("GameId", "RatingId");

                    b.HasIndex("RatingId");

                    b.ToTable("GameRating");
                });

            modelBuilder.Entity("AccountAPI.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PlatformTypeId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("PlatformId");

                    b.HasIndex("PlatformTypeId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7207),
                            Name = "Steam",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7427)
                        },
                        new
                        {
                            PlatformId = 2,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7654),
                            Name = "Microsoft Store",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7659)
                        },
                        new
                        {
                            PlatformId = 3,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7667),
                            Name = "Windows",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7670)
                        },
                        new
                        {
                            PlatformId = 4,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7677),
                            Name = "Android",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7679)
                        },
                        new
                        {
                            PlatformId = 5,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7685),
                            Name = "Steam VR",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7688)
                        },
                        new
                        {
                            PlatformId = 6,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7694),
                            Name = "Oculus",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7696)
                        },
                        new
                        {
                            PlatformId = 7,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7703),
                            Name = "Origin",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7705)
                        },
                        new
                        {
                            PlatformId = 8,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7712),
                            Name = "Uplay",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7714)
                        },
                        new
                        {
                            PlatformId = 9,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7721),
                            Name = "Epic",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7723)
                        },
                        new
                        {
                            PlatformId = 10,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7730),
                            Name = "Standalone",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7732)
                        },
                        new
                        {
                            PlatformId = 11,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7738),
                            Name = "Maniaplenet",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7740)
                        },
                        new
                        {
                            PlatformId = 12,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7747),
                            Name = "Play Station",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7749)
                        },
                        new
                        {
                            PlatformId = 13,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7755),
                            Name = "BattleNet",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7757)
                        },
                        new
                        {
                            PlatformId = 14,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7763),
                            Name = "Lego Mini Online",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7766)
                        },
                        new
                        {
                            PlatformId = 15,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7772),
                            Name = "League of Legends",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7774)
                        },
                        new
                        {
                            PlatformId = 16,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7780),
                            Name = "Intel Appup",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7782)
                        },
                        new
                        {
                            PlatformId = 17,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7789),
                            Name = "Cryptic Studios",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7791)
                        },
                        new
                        {
                            PlatformId = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7797),
                            Name = "Amazon",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7799)
                        },
                        new
                        {
                            PlatformId = 19,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7806),
                            Name = "McAfee LiveSafe",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7808)
                        },
                        new
                        {
                            PlatformId = 20,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7814),
                            Name = "Eve Online",
                            PlatformTypeId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7816)
                        },
                        new
                        {
                            PlatformId = 21,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7822),
                            Name = "Apple",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7824)
                        },
                        new
                        {
                            PlatformId = 22,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7831),
                            Name = "QQ",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7833)
                        },
                        new
                        {
                            PlatformId = 23,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7839),
                            Name = "Media Accounts",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7841)
                        },
                        new
                        {
                            PlatformId = 24,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7848),
                            Name = "Twitch",
                            PlatformTypeId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(7850)
                        });
                });

            modelBuilder.Entity("AccountAPI.Models.PlatformType", b =>
                {
                    b.Property<int>("PlatformTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("PlatformTypeId");

                    b.ToTable("PlatformTypes");

                    b.HasData(
                        new
                        {
                            PlatformTypeId = 1,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(3936),
                            Name = "Game",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(4184)
                        },
                        new
                        {
                            PlatformTypeId = 2,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(4430),
                            Name = "Other",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 322, DateTimeKind.Local).AddTicks(4434)
                        });
                });

            modelBuilder.Entity("AccountAPI.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Definition")
                        .IsRequired();

                    b.Property<string>("ImageLink")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("RatingsCountry")
                        .IsRequired();

                    b.Property<string>("RatingsSystem")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Age = 3,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4486),
                            Definition = "Titles rated EC (Early Childhood) have content that may be suitable for ages 3 and older. Contains no material that parents would find inappropriate.",
                            ImageLink = "client/images/ESRB/eC.png",
                            Name = "Early Childhood",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4696)
                        },
                        new
                        {
                            RatingId = 2,
                            Age = 6,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4917),
                            Definition = "Titles rated E (Everyone) have content that is generally suitable for all ages. May contain minimal cartoon, fantasy or mild violence and/or infrequent use of mild language.",
                            ImageLink = "client/images/ESRB/E.png",
                            Name = "Everyone",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4921)
                        },
                        new
                        {
                            RatingId = 3,
                            Age = 10,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4930),
                            Definition = "Titles rated E10+ (Everyone 10 and older) have content that is generally suitable for ages 10 and up. May contain more cartoon, fantasy or mild violence, mild language and/or minimal suggestive themes.themes.",
                            ImageLink = "client/images/ESRB/E10.png",
                            Name = "Everyone 10+",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4933)
                        },
                        new
                        {
                            RatingId = 4,
                            Age = 13,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4940),
                            Definition = "Titles rated T (Teen) have content that is generally suitable for ages 13 and up. May contain violence, suggestive themes, crude humor, minimal blood, simulated gambling, and/or infrequent use of strong language.",
                            ImageLink = "client/images/ESRB/T.png",
                            Name = "Teen",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4942)
                        },
                        new
                        {
                            RatingId = 5,
                            Age = 17,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4948),
                            Definition = "Titles rated M (Mature) have content that is generally suitable for persons ages 17 and up. May contain intense violence, blood and gore, sexual content and/or strong language.",
                            ImageLink = "client/images/ESRB/M.png",
                            Name = "Mature",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4951)
                        },
                        new
                        {
                            RatingId = 6,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4958),
                            Definition = "Titles rated AO (Adults Only) have content that is only suitable for persons ages 17 and up. May contain intense violence, blood and gore, sexual content and/or strong language.",
                            ImageLink = "client/images/ESRB/Ao.png",
                            Name = "Adults Only 18+",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4960)
                        },
                        new
                        {
                            RatingId = 7,
                            Age = -1,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4966),
                            Definition = "Titles listed as RP (Rating Pending) have not yet been assigned a final ESRB rating. (This symbol appears only in advertising and promotional materials prior to a game's release, and will be replaced by a game’s rating once it has been assigned.)",
                            ImageLink = "client/images/ESRB/RP.png",
                            Name = "Rating Pending",
                            RatingsCountry = "USA",
                            RatingsSystem = "ESRB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4968)
                        },
                        new
                        {
                            RatingId = 8,
                            Age = 3,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4975),
                            Definition = "The content of games with a PEGI 3 rating is considered suitable for all age groups. The game should not contain any sounds or pictures that are likely to frighten young children. A very mild form of violence (in a comical context or a childlike setting) is acceptable. No bad language should be heard.",
                            ImageLink = "client/images/PEGI/3.png",
                            Name = "PEGI 3",
                            RatingsCountry = "EU",
                            RatingsSystem = "PEGI",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4977)
                        },
                        new
                        {
                            RatingId = 9,
                            Age = 7,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4984),
                            Definition = "Game content with scenes or sounds that can possibly frightening to younger children should fall in this category. Very mild forms of violence (implied, non-detailed, or non-realistic violence) are acceptable for a game with a PEGI 7 rating.",
                            ImageLink = "client/images/PEGI/7.png",
                            Name = "PEGI 7",
                            RatingsCountry = "EU",
                            RatingsSystem = "PEGI",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4986)
                        },
                        new
                        {
                            RatingId = 10,
                            Age = 12,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4993),
                            Definition = "Video games that show violence of a slightly more graphic nature towards fantasy characters or non-realistic violence towards human-like characters would fall in this age category. Sexual innuendo or sexual posturing can be present, while any bad language in this category must be mild. Gambling as it is normally carried out in real life in casinos or gambling halls can also be present (e.g. card games that in real life would be played for money).",
                            ImageLink = "client/images/PEGI/12.png",
                            Name = "PEGI 12",
                            RatingsCountry = "EU",
                            RatingsSystem = "PEGI",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(4995)
                        },
                        new
                        {
                            RatingId = 11,
                            Age = 16,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5009),
                            Definition = "This rating is applied once the depiction of violence (or sexual activity) reaches a stage that looks the same as would be expected in real life. The use of bad language in games with a PEGI 16 rating can be more extreme, while games of chance, and the use of tobacco, alcohol or illegal drugs can also be present.",
                            ImageLink = "client/images/PEGI/16.png",
                            Name = "PEGI 16",
                            RatingsCountry = "EU",
                            RatingsSystem = "PEGI",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5011)
                        },
                        new
                        {
                            RatingId = 12,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5019),
                            Definition = "The adult classification is applied when the level of violence reaches a stage where it becomes a depiction of gross violence, apparently motiveless killing, or violence towards defenceless characters. The glamorisation of the use of illegal drugs and explicit sexual activity should also fall into this age category.",
                            ImageLink = "client/images/PEGI/18.png",
                            Name = "PEGI 18",
                            RatingsCountry = "EU",
                            RatingsSystem = "PEGI",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5021)
                        },
                        new
                        {
                            RatingId = 13,
                            Age = 0,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5028),
                            Definition = "Any age",
                            ImageLink = "client/images/RARS/0+.png",
                            Name = "0+",
                            RatingsCountry = "Russia",
                            RatingsSystem = "RARS",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5030)
                        },
                        new
                        {
                            RatingId = 14,
                            Age = 6,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5037),
                            Definition = "The age 6 and older",
                            ImageLink = "client/images/RARS/6+.png",
                            Name = "6+",
                            RatingsCountry = "Russia",
                            RatingsSystem = "RARS",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5039)
                        },
                        new
                        {
                            RatingId = 15,
                            Age = 12,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5045),
                            Definition = "The age 12 and older",
                            ImageLink = "client/images/RARS/12+.png",
                            Name = "12+",
                            RatingsCountry = "Russia",
                            RatingsSystem = "RARS",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5047)
                        },
                        new
                        {
                            RatingId = 16,
                            Age = 16,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5054),
                            Definition = "The age 16 and older",
                            ImageLink = "client/images/RARS/16+.png",
                            Name = "16+",
                            RatingsCountry = "Russia",
                            RatingsSystem = "RARS",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5056)
                        },
                        new
                        {
                            RatingId = 17,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5063),
                            Definition = "The age 18 and older",
                            ImageLink = "client/images/RARS/18+.png",
                            Name = "18+",
                            RatingsCountry = "Russia",
                            RatingsSystem = "RARS",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5065)
                        },
                        new
                        {
                            RatingId = 18,
                            Age = 0,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5071),
                            Definition = "Contains material available for general viewing. This category does not necessarily designate a children's film or game. Although not mandatory at this category, the Board may provide consumer information. Consumer advice at G classification usually relates to impacts on very young children. The content is very mild in impact.",
                            ImageLink = "client/images/ACB/E.png",
                            Name = "Exempt from classification",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5074)
                        },
                        new
                        {
                            RatingId = 19,
                            Age = 0,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5080),
                            Definition = "Contains material available for general viewing. This category does not necessarily designate a children's film or game. Although not mandatory at this category, the Board may provide consumer information. Consumer advice at G classification usually relates to impacts on very young children. The content is very mild in impact.",
                            ImageLink = "client/images/ACB/General.png",
                            Name = "General",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5082)
                        },
                        new
                        {
                            RatingId = 20,
                            Age = 8,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5089),
                            Definition = "Not recommended for viewing or playing by people under 15 without guidance from parents or guardians. Contains material that young viewers may find confusing or upsetting. The content is mild in impact.",
                            ImageLink = "client/images/ACB/PG.png",
                            Name = "Parental Guidance",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5091)
                        },
                        new
                        {
                            RatingId = 21,
                            Age = 15,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5098),
                            Definition = "Recommended for people aged 15 years and over. People under 15 may legally access this material because it is an advisory category. This category contains material that may require a mature perspective, but is not deemed too strong for younger viewers. The content is moderate in impact, although the Moderate indicator prefix is no longer used in the consumer advice, eg. Moderate violence is referred to as Violence.",
                            ImageLink = "client/images/ACB/M.png",
                            Name = "Mature",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5100)
                        },
                        new
                        {
                            RatingId = 22,
                            Age = 15,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5107),
                            Definition = "Contains material that is considered unsuitable for exhibition by persons under the age of 15. People under 15 may legally purchase, rent, exhibit or view such content only under the supervision of a parent or adult guardian. A person may be asked to show proof of age before renting or purchasing an MA 15+ film or computer game. The content is strong in impact.",
                            ImageLink = "client/images/ACB/MA.png",
                            Name = "Mature Accompanied",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5109)
                        },
                        new
                        {
                            RatingId = 23,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5115),
                            Definition = "Contains material that is considered unsuitable for exhibition to persons under the age of 18. People under 18 may not legally buy, rent, exhibit or view R 18+ classified content. A person may be asked for proof of their age before purchasing, hiring or viewing an R 18+ film or computer game at a retail store or cinema. Some material classified R 18+ may be offensive to sections of the adult community. The content is high in impact.",
                            ImageLink = "client/images/ACB/R18.png",
                            Name = "Restricted R",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5117)
                        },
                        new
                        {
                            RatingId = 24,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5124),
                            Definition = "Contains material that is pornographic in nature. People under 18 may not legally buy, rent, possess, exhibit or view these films. The exhibition or sale of these films to people under the age of 18 years is a criminal offence carrying a maximum fine of $5,500. Films classified as X 18+ are banned (via state government legislation) from being sold or rented in all Australian states (but are legal to possess except in certain parts of the Northern Territory) and are legally available to purchase only in the Australian Capital Territory and the Northern Territory. Importing X 18+ material from these territories to any other state is legal (as the Australian Constitution forbids any restrictions on trade between the states and territories). The content is sexually explicit, and the rating does not exist for video games.",
                            ImageLink = "client/images/ACB/X18.png",
                            Name = "Restricted X",
                            RatingsCountry = "Australia",
                            RatingsSystem = "ACB",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5126)
                        },
                        new
                        {
                            RatingId = 25,
                            Age = 0,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5133),
                            Definition = "Approved without age restriction in accordance with Art. 14 German Children and Young Persons Protection Act (JuSchG).  Games without age restriction are games which are directly aimed at children and young persons as well as at an adult buyer group.",
                            ImageLink = "client/images/USK/0.png",
                            Name = "0",
                            RatingsCountry = "Germany",
                            RatingsSystem = "USK",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5135)
                        },
                        new
                        {
                            RatingId = 26,
                            Age = 6,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5142),
                            Definition = "Approved for children aged 6 and above in accordance with Art. 14 German Children and Young Persons Protection Act (JuSchG).  These games mostly involve family-friendly games which may be more exciting and competitive (e.g. via faster game speeds and more complex tasks).",
                            ImageLink = "client/images/USK/6.png",
                            Name = "6",
                            RatingsCountry = "Germany",
                            RatingsSystem = "USK",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5144)
                        },
                        new
                        {
                            RatingId = 27,
                            Age = 12,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5151),
                            Definition = "Approved for children aged 12 and above in accordance with Art. 14 German Children and Young Persons Protection Act (JuSchG).  These games feature much more of a competitive edge. Game scenarios contain little violence, enabling players to distance themselves sufficiently from events.",
                            ImageLink = "client/images/USK/12.png",
                            Name = "12",
                            RatingsCountry = "Germany",
                            RatingsSystem = "USK",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5153)
                        },
                        new
                        {
                            RatingId = 28,
                            Age = 16,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5159),
                            Definition = "Approved for children aged 16 and above in accordance with Art. 14 German Children and Young Persons Protection Act (JuSchG).  Games approved for children aged 16 and above may include acts of violence. This means that it is also natural for adults to buy them.",
                            ImageLink = "client/images/USK/16.png",
                            Name = "16",
                            RatingsCountry = "Germany",
                            RatingsSystem = "USK",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5161)
                        },
                        new
                        {
                            RatingId = 29,
                            Age = 18,
                            CreatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5168),
                            Definition = "Not approved for anyone under 18 in accordance with Art. 14 German Children and Young Persons Protection Act (JuSchG).  These games almost always involve violent game concepts and frequently generate a dark and threatening atmosphere. This makes them suitable for adults only. These games often contain brutal, strong bloody violence and/or glorify war and/or human rights violations.",
                            ImageLink = "client/images/USK/18.png",
                            Name = "18",
                            RatingsCountry = "Germany",
                            RatingsSystem = "USK",
                            UpdatedAt = new DateTime(2019, 7, 1, 21, 48, 29, 323, DateTimeKind.Local).AddTicks(5170)
                        });
                });

            modelBuilder.Entity("AccountAPI.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("AccountAPI.Models.Account", b =>
                {
                    b.HasOne("AccountAPI.Models.Event", "Event")
                        .WithMany("Accounts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.AccountProfile", b =>
                {
                    b.HasOne("AccountAPI.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("AccountAPI.Models.AccountProfile", "AccountProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.Code", b =>
                {
                    b.HasOne("AccountAPI.Models.Game")
                        .WithMany("Codes")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("AccountAPI.Models.GameAccount", b =>
                {
                    b.HasOne("AccountAPI.Models.Account", "Account")
                        .WithMany("GameAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountAPI.Models.Game", "Game")
                        .WithMany("GameAccounts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.GameControllerType", b =>
                {
                    b.HasOne("AccountAPI.Models.ControllerType", "ControllerType")
                        .WithMany("GameControllerTypes")
                        .HasForeignKey("ControllerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountAPI.Models.Game", "Game")
                        .WithMany("GameControllerTypes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.GamePlatform", b =>
                {
                    b.HasOne("AccountAPI.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountAPI.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.GameRating", b =>
                {
                    b.HasOne("AccountAPI.Models.Game", "Game")
                        .WithMany("GameRatings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountAPI.Models.Rating", "Rating")
                        .WithMany("GameRatings")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccountAPI.Models.Platform", b =>
                {
                    b.HasOne("AccountAPI.Models.PlatformType", "PlatformType")
                        .WithMany("Platforms")
                        .HasForeignKey("PlatformTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
